name: domain
description: Domain package

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.1

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  http: ^0.13.5
  
  json_annotation: ^4.8.0  
  mockito: ^5.3.2

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  very_good_analysis: ^4.0.0

flutter:
